include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - always_declare_return_types
    - avoid_returning_null
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - comment_references
    - directives_ordering
    - invariant_booleans
    - no_adjacent_strings_in_list
    - omit_local_variable_types
    - only_throw_errors
    - prefer_interpolation_to_compose_strings
    - prefer_single_quotes
    - sort_pub_dependencies
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_statements
