name: flutter_map
description: A versatile mapping package for Flutter, that's simple and easy to learn, yet completely customizable and configurable
version: 6.0.0

repository: https://github.com/fleaflet/flutter_map
issue_tracker: https://github.com/fleaflet/flutter_map/issues
documentation: https://docs.fleaflet.dev

funding:
  - https://docs.fleaflet.dev/v/v6-1/supporters

topics:
  - flutter-map
  - map

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  async: ^2.9.0
  collection: ^1.16.0
  flutter:
    sdk: flutter
  http: ^1.0.0
  latlong2: ^0.9.0
  logger: ^2.0.1
  meta: ^1.8.0
  polylabel: ^1.0.1
  proj4dart: ^2.1.0
  vector_math: ^2.1.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  test: ^1.21.4

flutter:
  assets:
    - lib/assets/flutter_map_logo.png
