blank_issues_enabled: false
contact_links:
  - name: Get Help
    url: https://discord.gg/egEGeByf4q
    about: Don't quite understand how to implement something, or just want to talk? Join the Discord server!
  - name: Documentation
    url: https://docs.fleaflet.dev/
    about: Before posting an issue, please ensure you read the documentation thoroughly
