name: Deploy Web Example App (Push)
on:
  workflow_call:

jobs:
    deploy-push:
      name: "Deploy Web Example App"
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./example
      steps:
        - name: Download Web Artifact
          uses: actions/github-script@v6.4.1
          with:
            script: |
              var artifacts = await github.actions.listWorkflowRunArtifacts({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 run_id: ${{github.event.workflow_call.id}},
              });
              var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
                return artifact.name == "web-build"
              })[0];
              var download = await github.actions.downloadArtifact({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 artifact_id: matchArtifact.id,
                 archive_format: 'zip',
              });
              var fs = require('fs');
              fs.writeFileSync('${{github.workspace}}/web-build.zip', Buffer.from(download.data));
        - name: Unzip Web Artifact
          run: unzip web-build.zip
        - name: Publish Live Web App
          uses: FirebaseExtended/action-hosting-deploy@main
          with:
            repoToken: "${{ secrets.GITHUB_TOKEN }}"
            firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLEAFLET }}"
            channelId: live
            projectId: fleaflet-firebase