name: Deploy Web Example App (Push)
on:
  workflow_call:

jobs:
    deploy-push:
      name: "Deploy Web Example App"
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./example
      steps:
        - name: Download Web Artifact
          uses: actions/download-artifact@v3
          with:
            name: web-build
            path: example/build/web
        - name: Publish Live Web App
          uses: FirebaseExtended/action-hosting-deploy@main
          with:
            repoToken: "${{ secrets.GITHUB_TOKEN }}"
            firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLEAFLET }}"
            channelId: live
            projectId: fleaflet-firebase