name: Deploy Web Example App (Push)
on:
  workflow_call:

jobs:
    # This is a safe space: scripts must not be run on any user input (eg. files)
    deploy-push:
      name: "Deploy"
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
        - name: Download Web Artifact
          uses: actions/download-artifact@v3
          with:
            name: web-build
            path: example/build/web
        - name: Publish Live Web App
          uses: FirebaseExtended/action-hosting-deploy@main
          with:
            repoToken: "${{ secrets.GITHUB_TOKEN }}"
            firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLEAFLET }}"
            channelId: live
            projectId: fleaflet-firebase