name: Push CI/CD
on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: "Score, Analyse & Test"
    uses: ./.github/workflows/test.yml

  build:
    name: "Build Example Apps"
    needs: test
    uses: ./.github/workflows/build.yml