name: Push CI/CD
on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  sat-build:
    name: "SAT & Build"
    uses: ./.github/workflows/sat-build.yml

  deploy:
    name: "Deploy Web Example App"
    needs: sat-build
    uses: ./.github/workflows/deploy-push.yml